<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-PRN3QSKO" failures="3" tests="6" name="runner.TestRunner" time="30.691" errors="0" timestamp="2022-07-12T20:41:51 EEST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="4.456"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="9.115"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.569">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at steps_defs.CommonStepsDefs.checkErrorMessage(CommonStepsDefs.java:33)
at ✽.Then I see login error message 'Epic sadface: Username is required’(file:///C:/Users/janis/IdeaProjects/qa_automation_jm/src/test/resources/features/login.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.544">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at steps_defs.CommonStepsDefs.checkErrorMessage(CommonStepsDefs.java:33)
at ✽.Then I see login error message 'Epic sadface: Username is required’(file:///C:/Users/janis/IdeaProjects/qa_automation_jm/src/test/resources/features/login.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="6.201"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.806">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at steps_defs.CommonStepsDefs.checkErrorMessage(CommonStepsDefs.java:33)
at ✽.Then I see login error message 'Epic sadface: Username is required’(file:///C:/Users/janis/IdeaProjects/qa_automation_jm/src/test/resources/features/login.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
